#!/bin/sh

#indent -kr -brf --tab-size 8 -ut -l180 src/parser.cc
# TODO: SortIncludes: false
clang-format -i --style='{BasedOnStyle: LLVM, IndentWidth: 8, TabWidth: 8, UseTab: Always, BreakBeforeBraces: Attach, ColumnLimit: 0, PointerAlignment: Left, ReferenceAlignment: Left}' src/parser.cc
